name: Deploy Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/aya-registry/prompts-to-firestore:${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authorize with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t $IMAGE --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE }} \
            --image $IMAGE \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated
