name: Prompt Sync

on:
  push:
    paths:
      - 'docs/prompts/**'
      - '.github/workflows/prompt_sync.yml'
  workflow_dispatch:

jobs:
  sync-prompts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: aya-shared
          service_account_key: ${{ secrets.GCS_DEPLOY_KEY }}
          export_default_credentials: true

      - name: Rsync prompts to GCS
        run: |
          gsutil -m rsync -r docs/prompts gs://aya-shared/prompts

      - name: Trigger Pub/Sub notification
        run: |
          for f in docs/prompts/*; do
            base=$(basename "$f")
            gcloud pubsub topics publish prompt-updated --message="{\"role\": \"${base%.txt}\"}"
          done

