name: Prompt Sync

on:
  push:
    paths:
      - 'docs/prompts/**'
      - '.github/workflows/prompt_sync.yml'
  workflow_dispatch:

jobs:
  sync-prompts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authorize with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Rsync prompts to GCS
        run: |
          gsutil -m rsync -r docs/prompts gs://aya-shared/prompts

      - name: Trigger Pub/Sub notification
        run: |
          for f in docs/prompts/*; do
            base=$(basename "$f")
            gcloud pubsub topics publish prompt-updated --message="{\"role\": \"${base%.txt}\"}"
          done

